struct View_Settings {
  circular_particles: bool;
  render_rotation: bool;
  render_bonds: bool;
  colors: bool;
  random_colors: bool;
  color_code_rotation: bool;
}

struct Setup_Settings {
  particles: int;
  max_radius: float;
  variable_rad: bool;
  holeyness: float;
  max_h_velocity: float;
  min_h_velocity: float;
  max_v_velocity: float;
  min_v_velocity: float;
  grid_width: float;
  hex_grid: bool;
}

struct Simulation_Settings {
  timestep: float;
  gen_per_frame: int;
  auto_width: bool;
  width: float;
  height: float;
  maintain_ar: bool;
  round_walls: bool;
  wall_radius: float;
}

struct Physics_Settings {
  gravity: bool;
  g_force: float;
  planet_mode: bool;
  mouse_gravity: bool;
  collisions: bool;
  friction_coef: float;
  bond: int;
  bond_normal_stiffness: float;
  bond_shear_stiffness: float;
  bond_normal_strength: float;
  bond_shear_strength: float;
  moment_contribution_factor: float;
}

struct Settings {
  view_settings: View_Settings;
  setup_settings: Setup_Settings;
  sim_settings: Simulation_Settings;
  physics_settings: Physics_Settings;
}

table State {
  pos: [float];
  vel: [float];
  acc: [float];
  rot: [float];
  rot_vel: [float];
  rot_acc: [float];
  forces: [float];
  radii: [float];
  fixity: [int];
  bonds: [int];
  contacts: [float];
  material_pointers: [int];
  materials: [float];
  settings: Settings;
}

root_type State;