name: Rust

on:
  push:
    branches: [ "origin" ]
  pull_request:
    branches: [ "origin" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install cross
      run: cargo install cross
    
    - name: Windows Build
      run: cross build --release --target x86_64-pc-windows-gnu

    - name: MacOS(ARM) Build
      run: |
        rustup target add aarch64-apple-darwin
        cross build --release --target aarch64-apple-darwin
      
    - name: MacOS(x86-64) Build
      run: |
        rustup target add x86_64-apple-darwin
        cross build --release --target x86_64-apple-darwin
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
    
    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/x86_64-pc-windows-gnu/release/PS.exe
        asset_name: PS-windows.exe
        asset_content_type: application/vnd.microsoft.portable-executable
    - name: Upload MacOS(ARM) Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/aarch64-apple-darwin/release/PS
        asset_name: PS-macos-arm
        asset_content_type: application/octet-stream
    - name: Upload MacOS(x86-64) Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/x86_64-apple-darwin/release/PS
        asset_name: PS-macos-x86_64
        asset_content_type: application/octet-stream
