name: Rust

on:
  push:
    branches: [ "origin" ]
  pull_request:
    branches: [ "origin" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release: 
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Calculate Previous Run Number
      id: previous_run_number
      run: echo "::set-output name=run_number::$((${{ github.run_number }} - 44))"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.previous_run_number.outputs.run_number }}
        name: v${{ steps.previous_run_number.outputs.run_number }}
  win-build:
    runs-on: windows-latest
    needs: release
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: target/release/PS.exe
        asset_name: PS.exe
        asset_content_type: application/vnd.microsoft.portable-executable

  osx-build:
    runs-on: macos-latest
    needs: release
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: target/release/PS
        asset_name: PS
        asset_content_type: application/octet-stream
